In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


### Training the Model

In [ ]:
#Train
!python "/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/main.py" --method centernet --quick_prototype  --config_file "/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/configs/detection_resnet50_3x_noam_layers_affine.yml" --max_epochs 200 --decoder_attention scse

### Testing the Model (using pretrained model)

In [ ]:
#Test
!python "/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/main.py" --method centernet --gpu 0 --config_file "/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/configs/detection_resnet50_3x_coam_layers_affine.yml" --decoder_attention scse --test_from_checkpoint "/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/pretrained-resnet50-3x-coam-scSE-affine.ckpt"

/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2022-12-04 21:41:08.326 | INFO     | __main__:print_args:22 - {'encoder': 'resnet50', 'attention': 'coam', 'coam_layer_data': [3, [2048, 1024, 512], [256, 128, 64]], 'lr': 0.0001, 'weight_decay': 0.0005, 'batch_size': 16, 'test_batch_size': 16, 'num_dataloader_workers': 8, 'datasets': {'train_dataset': {'name': 'kubric', 'class': 'KubricChange', 'args': {'path_to_dataset': '/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/data_dir/Cross-data', 'split': 'train', 'method': 'centernet'}}, 'val_dataset': {'name': 'kubric', 'class': 'KubricChange', 'args': {

### Running Demo File

In [ ]:
#Demo Files
!python '/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/demo_single_pair.py' --load_weights_from '/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/pretrained-resnet50-3x-coam-scSE-affine.ckpt' --config_file "/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/configs/detection_resnet50_3x_coam_layers_affine.yml" --decoder_attention scse

In [ ]:
!ls '/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/data_dir/Cross_data'

### Function Testing/Editing

In [ ]:
import numpy as np
with open('/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/data_dir/Cross_data/metadata.npy', 'rb') as f:
  a = np.load(f)

print(a)

In [ ]:
from scipy.ndimage import label as label_connected_components
from einops import rearrange
mask_path = '/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/data_dir/Cross-data/mask_0_0_1_00000.png'
pil_image = Image.open(mask_path)
mask_as_np_array = np.array(pil_image)
print(mask_as_np_array.shape)
(
    connected_components,
    number_of_components,
) = label_connected_components(mask_as_np_array)
print("====Connected components====")
print(connected_components)
print("====Number of components====")
print(number_of_components)
if(number_of_components != 0):
  masks = []
  for i in range(number_of_components):
      masks.append(connected_components == i + 1)
  masks = rearrange(masks, "c h w -> h w c")


(256, 256)
====Connected components====
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
====Number of components====
6


## Environment Setup

In [ ]:
import sys
# !conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c  --prefix {sys.prefix} pytorch
!pip install -r "/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/requirements.txt"
!pip install pytorch-lightning Cython matplotlib ninja opencv-python scikit-image wandb loguru yacs easydict shapely pre-commit pycocotools h5py einops
!pip install segmentation-models-pytorch@git+https://github.com/ragavsachdeva/segmentation_models.pytorch.git@dc6009cc57f4d45662c4e838b5daf26663df4f7c
!pip install kornia@git+https://github.com/kornia/kornia@77589a58be6c603b7afd755d261783bd0c152a97
!pip install 'git+https://github.com/facebookresearch/detectron2.git'
!pip install -r "/content/drive/MyDrive/Fall 2022/CS 5824/The-Change-You-Want-to-See/req.txt"
# !python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html
#!pip install mmcv-full==1.4.4
!pip install mmdet

In [ ]:
!pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12/index.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.openmmlab.com/mmcv/dist/cu113/torch1.12/index.html
     |████████████████████████████████| 43.6 MB 2.0 MB/s 
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
  Using cached yapf-0.32.0-py2.py3-none-any.whl (190 kB)


In [ ]:
!pip uninstall pytorch-lightning
!pip install pytorch-lightning==1.6

In [ ]:
!pip install torchtext

In [ ]:
!pip install -r "/content/drive/MyDrive/The-Change-You-Want-to-See/requirements.txt"

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/facebookresearch/detectron2.git (to revision 2d6106bb9251f388fdac0ce21c50514fba827fb4) to /tmp/pip-install-_kkwkebw/detectron2_712c2c1962154581a8e0e9a1a9746d3b
  Running command git clone -q https://github.com/facebookresearch/detectron2.git /tmp/pip-install-_kkwkebw/detectron2_712c2c1962154581a8e0e9a1a9746d3b
  Running command git rev-parse -q --verify 'sha^2d6106bb9251f388fdac0ce21c50514fba827fb4'
  Running command git fetch -q https://github.com/facebookresearch/detectron2.git 2d6106bb9251f388fdac0ce21c50514fba827fb4
  Running command git checkout -q 2d6106bb9251f388fdac0ce21c50514fba827fb4
     |████████████████████████████████| 12.8 MB 1.7 MB/s 
Processing /colabtools/dist/google-colab-1.0.0.tar.gz
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/colabtools/dist/google-colab-1.0.0.tar.gz'



In [ ]:
!pip install -r "/content/drive/MyDrive/CS 5824/The-Change-You-Want-to-See-main/requirements/option2.txt"
!pip install setuptools==58.2.0
!pip install mmdet==2.20.0
!pip install mmcv-full==1.4.4
!python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html

In [ ]:
!pip install pytorch-lightning Cython matplotlib ninja opencv-python scikit-image wandb loguru yacs easydict shapely pre-commit pycocotools h5py einops
!pip install segmentation-models-pytorch@git+https://github.com/ragavsachdeva/segmentation_models.pytorch.git@dc6009cc57f4d45662c4e838b5daf26663df4f7c
!pip install kornia@git+https://github.com/kornia/kornia@77589a58be6c603b7afd755d261783bd0c152a97
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'